remote_theme: just-the-docs/just-the-docs@v0.9.0

plugins:
  - jekyll-seo-tag

title: "FFXIV Elemental Raid Macros"
description: "Final Fantasy XIV Elemental DC Raid Macros"

favicon_ico: "favicon.ico"

color_scheme: dark

aux_links:
  "Elemental DC Raid Macros Discord":
    - "https://discord.gg/WEzhVHwAU6"
  "Github":
    - "https://github.com/Tuufless/FFXIV-Elemental-raid-macros"

aux_links_new_tab: true
nav_external_links_new_tab: true

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

collections:
  current:
    permalink: "/:collection/:path/"
    output: true
  raids:
    permalink: "/:collection/:path/"
    output: true
  ultimates:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    current:
      name: 7.0 Dawntrail
    ultimates:
      name: Ultimates
    raids:
      name: Archives
